config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    #confirmations: 'users/confirmations'
  }

  resources :users

  namespace :admin do
    resources :settings
    resources :galaxies
  end

  root 'pages#index'

end

app/models/account.rb
require 'securerandom'
require 'digest'

class Account < ActiveRecord::Base
  attribute :admin_level, :integer, :limit => 1

  def self.register(user)
    salt = SecureRandom.hex(Setting.salt_length)
    account = Account.create!(
      username: user[:username],
      salt: salt,
      password: Digest::SHA256.hexdigest(Setting.db_secret + user[:password] + salt),
      active: false,
      station_id: Random.new.rand(4294967295))
    return account.account_id
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/galaxy.rb
class Galaxy < ApplicationRecord
    self.table_name = "galaxy"
end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  cache_prefix { "v1" }

  # Define your fields
  # field :host, type: :string, default: "http://localhost:3000"
  # field :default_locale, default: "en", type: :string
  # field :confirmable_enable, default: "0", type: :boolean
  # field :admin_emails, default: "admin@rubyonrails.org", type: :array
  # field :omniauth_google_client_id, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] || ""), type: :string, readonly: true
  # field :omniauth_google_client_secret, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] || ""), type: :string, readonly: true
  field :db_secret, default: "swgemus3cr37!"
  field :salt_length, default: 12
  field :theme, default: "Default"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :encryptable
  self.table_name = :citadel_users
  has_one :account

end

app/controllers/admin/galaxies_controller.rb
module Admin

  class GalaxiesController < ApplicationController

    before_action :get_galaxy_id, only: [:edit, :update, :destroy]

      def index
          @galaxies = Galaxy.all
      end
      
      def new
        @galaxy = Galaxy.new
      end

      def create
        @galaxy = Galaxy.create(galaxy_params)
        if @galaxy
          @galaxy.save
          redirect_to admin_galaxies_path
        else
          render :new
        end 
      end
    
      def edit
      end
    
      def update
        if @galaxy.update_attributes(galaxy_params)
          @galaxy.save
          flash[:notice] = "Galaxy updated."
          redirect_to admin_galaxies_path
        else
          flash[:error] = "Could not update Galaxy."
          render :edit
        end
      end  
    
      def show
      end

      def destroy
        @galaxy.destroy
        redirect_to admin_galaxies_path, :notice => "Galaxy #{@galaxy.name} was deleted"
      end
        
        private
          def galaxy_params
            params.require(:galaxy).permit(:galaxy_id, :name, :address, :port, :pingport, :population)
          end 
          def get_galaxy_id
            @galaxy = Galaxy.find_by(galaxy_id: params[:id]) || Galaxy.new(galaxy_id: params[:id])
          end
  end
end

app/controllers/admin/settings_controller.rb
module Admin
  class SettingsController < ApplicationController
    before_action :get_setting, only: [:edit, :update]

    def index
      @settings = Setting.get_all
    end

    def edit
    end

    def update
      if @setting.value != params[:setting][:value]
        @setting.value = params[:setting][:value]
        @setting.save
        redirect_to admin_settings_path, notice: 'Setting has updated.'
      else
        redirect_to admin_settings_path
      end
    end

    def get_setting
      @setting = Setting.find_by(var: params[:id]) || Setting.new(var: params[:id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
require 'byebug'

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # POST /resource
  def create
    super
    user = User.find_by(email: params[:user][:email])
    user.update(account_id: Account.register({username: params[:user][:username], password: params[:user][:password]}))
    user.save!
  end

  # PUT /resource
  def update
    account_id = @user.account_id
    super
    if params[:user][:password] != nil then
      AccountSyncService.password_sync(
        id: account_id, 
        password: params[:user][:password]
        )
    end
  end

  # DELETE /resource
  def destroy
    super
    account_id = @user.account_id
    AccountSyncService.destroy(account_id)
  end

  protected
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

require 'securerandom'
require 'digest'

# Users Controller
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.register(params[:new])
    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    User.update_details(params[:id], params[:user])
    redirect_to users_path
  end  

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/devise_helper.rb
module DeviseHelper

    def devise_error_messages!
      return '' if resource.errors.empty?
      messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
      html = <<-HTML
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
          <strong>
            #{pluralize(resource.errors.count, "error")} must be fixed
          </strong>
          #{messages}
        </div>
        HTML
      html.html_safe
    end

  end

app/helpers/galaxies_helper.rb
module GalaxiesHelper

end

app/helpers/settings_helper.rb
module SettingsHelper

  def themesList
    initialList = Dir.entries(Rails.root.join("app/assets/stylesheets/themes")).select! { |x| x =~ /^[a-zA-Z ]*$/ }.sort
    themesList = []
    #The puts statements are for debugging the inner workings of the themes list search.
    puts "== Initial List Array ---> " + initialList.inspect
    puts "============================================================="
    puts "== Searching for themes in app/assets/stylesheets/themes ===="
    puts "============================================================="
        initialList.each do |t|
            t = t.sub(".scss", "")
            puts "== Theme " + t + " detected!"
            themesList.push(t)
        end
    puts "============================================================="
    puts "== Finished searching themes ================================"
    puts "============================================================="
    themesList.sort!
    puts "== Themes List Array ---> " + themesList.inspect
    return themesList
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/admin/galaxies/_form.html.erb
<div class="form-group">
    <%= f.label :galaxy_id %>
    <%= f.text_field :galaxy_id, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :port %>
    <%= f.text_field :port, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :pingport %>
    <%= f.text_field :pingport, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :population %>
    <%= f.text_field :population, class: "form-control" %>
</div>

<div class="form-group float-right">
    <%= link_to "Cancel", admin_galaxies_path, {class: "btn btn-secondary", role: "button"} %>
    <%= f.submit "Submit", {class: "btn btn-primary", role: "button"} %>
</div>

app/views/admin/galaxies/edit.html.erb
<div class="container">
  <div class="card mb-2">
    <div class="card-header">Edit Galaxy: <%= @galaxy.name %></div>
    <div class="card-body">
      <%= form_for(@galaxy, url: admin_galaxy_path(@galaxy.galaxy_id), method: 'patch') do |f| %>
        <%= render partial: 'form', locals: { f: f } %>
      <% end %>
    </div>  
  </div>
</div>

app/views/admin/galaxies/index.html.erb
<div class="container-fluid">
  <div class="card card-primary">
    <div class="card-header">
      Galaxies <%= link_to 'Add New Galaxy', new_admin_galaxy_path, {class: "btn btn-success btn-sm ml-2", role: "button"}%>
      </div>  
    <div class="card-body">
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th>Galaxy_ID</th>
            <th>Name</th>
            <th>Address</th>
            <th>Port</th>
            <th>PingPort</th>
            <th>Population</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
            <% @galaxies.each do |galaxy| %>
              <tr>
                <td> <%= galaxy.galaxy_id %> </td>
                <td> <%= galaxy.name %> </td>
                <td> <%= galaxy.address %> </td>
                <td> <%= galaxy.port %> </td>
                <td> <%= galaxy.pingport %> </td>
                <td> <%= galaxy.population %> </td>
                <td>
                  <%= link_to 'Edit', edit_admin_galaxy_path(galaxy.galaxy_id), {class: "btn btn-primary", role: "button"}%> 
                  <%= link_to 'Delete', admin_galaxy_path(galaxy.galaxy_id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                </td>
              </tr>
            <% end %>
          </tbody>
    </div>
  </div>
</div>

app/views/admin/galaxies/new.html.erb
<div class="container">
  <div class="card mb-2">
    <div class="card-header">New Galaxy</div>
    <div class="card-body">
      <%= form_for(@galaxy, url: admin_galaxies_path, method: 'post') do |f| %>
        <%= render partial: 'form', locals: { f: f } %>
      <% end %>
    </div>  
  </div>
</div>

app/views/admin/settings/edit.html.erb
<div class="container">
  <%= form_for(@setting, url: admin_setting_path(@setting.var), method: 'patch') do |f| %>

    <% case @setting.var %>
      <% when "theme" %>
          <label><%= @setting.var %></label>
            <%= f.select(:value, themesList.map { |value| [ value, value ]} ) %>
      <% else %> 
        <label><%= @setting.var %></label>
        <%= f.text_area :value, rows: 10 %>
      <% end %>
    <%= f.submit %>

  <% end %>
</div>

app/views/admin/settings/index.html.erb
<div class="container-fluid">
  <div class="card card-primary">
    <div class="card-header">Site Settings</div>
    <div class="card-body">
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col" colspan="2">Value</th>
          </tr>
          </thead>
          <tbody>
          <% @settings.each_key do |key| %>
            <tr>
              <th scope=row><%= key %></th>
              <td><%= Setting[key] %></td>
              <td><%= link_to 'edit', edit_admin_setting_path(key) %></td>
            </tr>
          <% end %>
          </tbody>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Citadel</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application' ,media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "themes/#{Setting.theme}/stylesheet" ,media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/partials/navigation' %>
    </header>
    <main role="main">
      <div class="container">
        <%= render 'layouts/partials/messages' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/partials/_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <ul>
            <li>
                <%= value %>
            </li>
        </ul>
    </div>
<% end %>

app/views/layouts/partials/_navigation.html.erb
<nav class="nav navbar-nav navbar-expand-lg navbar-dark mb-2">
  <div class="collapse navbar-collapse" id="navbarToggler">
  <!--<a class="navbar-brand" href="#">Citadel</a>-->
  <%= link_to("Citadel", root_path, class: "navbar-brand") %>
  <ul class="ul navbar-nav mr-auto mt-2 mt-lg-0">
    <li class="nav-item"><%= link_to 'Users', users_path, {class: "nav-link"} %></li>
    <li class="nav-item"><%= link_to 'Galaxies', admin_galaxies_path, {class: "nav-link"}%></li>
    <li class="nav-item"><%= link_to 'Settings', admin_settings_path, {class: "nav-link"}%></li>
    </ul>
  </div>

  <div class="navbar-right">
  <ul class="nav justify-content-end">
    <!-- Trigger the Login modal with a button -->
    <button type="button" class="btn" data-toggle="modal" data-target="#myModal">Login</button>
  </ul>
  </div>
</nav>

<!-- Login Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Login</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
      				<form class="form-horizontal"  method="post" accept-charset="UTF-8">
     				    <input id="sp_uname" class="txtBoxDefault login" type="text" name="sp_uname" placeholder="Username.."/>
				        <input id="sp_pass" class="txtBoxDefault login" type="password" name="sp_pass" placeholder="Password.."/>
              </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" type="submit" name="btnLogin" value="Login">Login</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<p> <%= link_to "Sign Up", new_user_registration_path %> </p>
<p> <%= link_to "Sign In", new_user_session_path %> </p>
<p> <%= link_to('Logout', destroy_user_session_path, method: :delete) %> </p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<table class="table table-striped table-hover">
    <div class="row">
    <hr />
        <div class="col-lg-6">
            <tr>
                <th>User ID</th>
                <th>User Name</th>
                <th>Email</th>
                <th colspan="2">Created</th>
            </tr>
            <% @users.each do |user| %>
                <tr>
                <td><%= user.id %></td>
                <td><%= user.username %></td>
                <td><%= user.email %></td>
                <td><%= link_to 'View Details', action: :show, id: user.id %>
                </tr>
            <% end %>
        </div>
    </div>
</table>

app/views/users/new.html.erb
<h1>Users#new</h1>
<%= form_tag({:action => 'create' }, :multipart => true) do %>
    Username: <%= text_field("new", "name") %>
    <br />
    Password: <%= password_field("new", "pass") %>
    <br />
    Email: <%= text_field("new", "email" ) %>
    <br />
    <%= submit_tag("Register") %>
<% end %>

app/views/users/show.html.erb
<% #TODO be able to list character info %>

<div class="container">
  <div class="card mb-2">
    <div class="card header">Details for: <%= @user.username %></div>
    <div class="card body">
      <% User.column_names.each do |column_name| %>
        <% next if column_name == "password" %>
        <div class="row">
          <div class="col"><%= column_name %></div>
          <div class="col"><%= @user.send(column_name) %></div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="card mb-2">
    <div class="card header">Server Account Details:</div>
    <div class="card body">
      <% Account.column_names.each do |column_name| %>
        <% next if column_name == "password" || column_name == "salt" %>
        <div class="row">
          <div class="col"><%= column_name %></div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="float-right">
    <%= link_to "Close", users_path, {class: "btn btn-secondary", role: "button"} %>
    <%= link_to "Edit", edit_user_path(@user), {class: "btn btn-primary", role: "button"} %>
</div>